In [1]:
import pandas as pd
import numpy as np

In [2]:
poverty = pd.read_csv('/Users/ankitakhatri/Downloads/Poverty2023.csv', encoding='latin-1')
education = pd.read_csv('/Users/ankitakhatri/Downloads/Education2023.csv', encoding='latin-1')
unemployment = pd.read_csv('/Users/ankitakhatri/Downloads/Unemployment2023.csv', encoding='latin-1')
population = pd.read_csv('/Users/ankitakhatri/Downloads/PopulationEstimates.csv', encoding='latin-1')

In [3]:
poverty.head()
poverty['Dataset'] = 'poverty'

In [4]:
education.head()
education['Dataset'] = 'education'

In [5]:
unemployment.head()
unemployment['Dataset'] = 'unemployment'

In [6]:
population.head()
population['Dataset'] = 'population'

In [7]:
# rename columns to match a standard format
poverty = poverty.rename(columns={'Stabr': 'State'})
education = education.rename(columns={'FIPS Code': 'FIPS_Code', 'Area name': 'Area_Name'})
population = population.rename(columns={'FIPStxt': 'FIPS_Code'})

In [10]:
# combine all dfs
combined_data = pd.concat([poverty, education, unemployment, population], ignore_index=True)

,FIPS_Code,State,Area_Name,Attribute,Value,Dataset
4833,6001,CA,Alameda County,Rural_Urban_Continuum_Code_2013,1.0,poverty
4834,6001,CA,Alameda County,Urban_Influence_Code_2013,1.0,poverty
4835,6001,CA,Alameda County,Rural_Urban_Continuum_Code_2023,1.0,poverty
4836,6001,CA,Alameda County,Urban_Influence_Code_2024,1.0,poverty
4837,6001,CA,Alameda County,POVALL_2023,151872.0,poverty

In [11]:
# data cleaning

# remove all other states except california
combined_data = combined_data[combined_data['State'] == "CA"]

# remove general california data, keep county data
combined_data = combined_data[combined_data['Area_Name'] != "California"]

# remove data not from 2023
regex_other_years = r'(?<!\d)(?!2023(?!\d))\d+'
combined_data = combined_data[~combined_data['Attribute'].str.contains(regex_other_years, regex=True, na=False)]

In [12]:

combined_data.to_csv('/Users/ankitakhatri/Downloads/CombinedData.csv', index=False)

combined_data.head()

,FIPS_Code,State,Area_Name,Attribute,Value,Dataset
4835,6001,CA,Alameda County,Rural_Urban_Continuum_Code_2023,1.0,poverty
4837,6001,CA,Alameda County,POVALL_2023,151872.0,poverty
4840,6001,CA,Alameda County,PCTPOVALL_2023,9.5,poverty
4855,6001,CA,Alameda County,MEDHHINC_2023,119230.0,poverty
4860,6003,CA,Alpine County,Rural_Urban_Continuum_Code_2023,8.0,poverty