In [1]:
import pandas as pd
import numpy as np

In [2]:
poverty = pd.read_csv('/Users/ankitakhatri/Downloads/Poverty2023.csv', encoding='latin-1')
education = pd.read_csv('/Users/ankitakhatri/Downloads/Education2023.csv', encoding='latin-1')
unemployment = pd.read_csv('/Users/ankitakhatri/Downloads/Unemployment2023.csv', encoding='latin-1')
population = pd.read_csv('/Users/ankitakhatri/Downloads/PopulationEstimates.csv', encoding='latin-1')

In [3]:
poverty.head()

   FIPS_Code Stabr      Area_Name        Attribute       Value
0          0    US  United States      POVALL_2023  40763043.0
1          0    US  United States   CI90LBALL_2023  40485829.0
2          0    US  United States   CI90UBALL_2023  41040257.0
3          0    US  United States   PCTPOVALL_2023        12.5
4          0    US  United States  CI90LBALLP_2023        12.4

In [4]:
education.head()

,FIPS Code,State,Area name,Attribute,Value
0,0,US,United States,"Less than a high school diploma, 1970",52373312.0
1,0,US,United States,"High school diploma only, 1970",34158051.0
2,0,US,United States,"Some college (1-3 years), 1970",11650730.0
3,0,US,United States,"Four years of college or higher, 1970",11717266.0
4,0,US,United States,Percent of adults with less than a high school...,47.7

In [5]:
unemployment.head()

   FIPS_Code State      Area_Name                  Attribute        Value
0          0    US  United States  Civilian_labor_force_2000  142601576.0
1          0    US  United States              Employed_2000  136904853.0
2          0    US  United States            Unemployed_2000    5696723.0
3          0    US  United States     Unemployment_rate_2000          4.0
4          0    US  United States  Civilian_labor_force_2001  143786537.0

In [6]:
population.head()

   FIPStxt State      Area_Name            Attribute        Value
0        0    US  United States      CENSUS_2020_POP  331449281.0
1        0    US  United States  ESTIMATES_BASE_2020  331464948.0
2        0    US  United States    POP_ESTIMATE_2020  331526933.0
3        0    US  United States    POP_ESTIMATE_2021  332048977.0
4        0    US  United States    POP_ESTIMATE_2022  333271411.0

In [7]:
# rename columns to match a standard format
poverty = poverty.rename(columns={'Stabr': 'State'})
education = education.rename(columns={'FIPS Code': 'FIPS_Code', 'Area name': 'Area_Name'})
population = population.rename(columns={'FIPStxt': 'FIPS_Code'})

In [9]:
# combine all dfs
combined_data = pd.concat([poverty, education, unemployment, population], ignore_index=True)

combined_data.to_csv('/Users/ankitakhatri/Downloads/CombinedData.csv', index=False)

combined_data.head()